# Generated by Django 4.0.3 on 2022-03-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text', models.TextField(max_length=500)),
                ('view', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'postings',
            },
        ),
        migrations.DeleteModel(
            name='Cloth',
        ),
    ]
